#include <iostream>
#include <sstream>
//#include "42.cpp"
//#include "43.cpp"
//#include "44.cpp"
//#include "45.cpp"
//#include "46.cpp"
//#include "47.cpp"
//#include "48.cpp"
//#include "49.cpp"
//#include "50.cpp"
//#include "51.cpp"
//#include "52.cpp"
//#include "53.cpp"
//#include "BinaryTree.cpp"
//#include "54.cpp"
//#include "55.cpp"
//#include "56.cpp"
//#include "57.cpp"
//#include "58.cpp"
//#include "59.cpp"
//#include "60.cpp"
//#include "61.cpp"
//#include "62.cpp"
//#include "63.cpp"
//#include "64.cpp"
//#include "65.cpp"
//#include "66.cpp"
//#include "67.cpp"
//#include "68.cpp"
//#include "3.cpp"
//#include "21.cpp"
//#include "quicksort.cpp"
//#include "TheLastKNode.cpp"
//#include "reverseList.cpp"
//#include "mergedSortedList.cpp"
//#include "7.cpp"
//#include "9.cpp"
//#include "11.cpp"
//#include "12.cpp"
//#include "14.cpp"
#include "33.cpp"
using namespace std;
int main() {
    Solution::solution();
    return 0;
}
